services:
  backend:
    build:
      context: ./pictionary-server # Ruta al directorio de tu backend
    container_name: flask-backend
    ports:
      - "5000:5000" # Mapea el puerto 8000 del contenedor al puerto 8000 del host
    environment:
      - FLASK_APP=server-pictionary.py
      - FLASK_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
